### ISSUE TITLE
Front End da Aplicação: dúvidas e sugestões.

### ISSUE THREAD

**Issue by betodasilva** [felipefanucchi/buscapramim_api#4]
Fala, @felipefanucchi. Beleza?

Vi o projeto através do @Filipe-Souza e, na curiosidade, vim ver do que se tratava e fiquei interessado em contribuir com o projeto.

Pensei inicialmente em contribuir na construção do backend em node, que estou aprendendo de uns tempos pra cá, mas como você (e talvez o souza) estão fazendo esta parte, de repente seja mais vantajoso pro andamento do projeto eu contribuir no front.

Já pensou em alguma stack? Tem design pra ser feito?

Se puder dar uma sugestão, podemos fazer em [next](https://github.com/zeit/next.js/) e [react](https://github.com/facebook/react).

Me fala aí o que acha da sugestão ou se prefere alguma outra coisa.

Tô aqui a disposição.

Abç

**Comment by felipefanucchi** [comment]
Cara, fico muito feliz em saber que está disposto a ajudar <3 

Inicialmente, pensei em um app com react native, utilizando redux pro state management e utilizando geolocalização.

A ideia é que após realizar o login, o usuário possa escolher entre, ajudar ou ser ajudado.

Caso ele queira ajudar, ele abrirá um mapa onde vê as pessoas, ao clicar, pode ver as necessidades e contata-las, a principio só pensei em colocar um botão de ligar, ou whatsapp, onde vai abrir uma conversa com uma mensagem pre pronta.

Caso ele queira ser ajudado, ele pode visualizar uma lista com as pessoas mais proximas, ou até mesmo, o mapa, e também contata-las.

Ainda não me decidi como essa visualização pode ser, com mapa, ou somente uma listagem com a distancia em metros/kms e caso ele queira pode traçar uma rota ate a pessoa e podemos abrir o Waze (nao sei se o waze tem alguma api onde vc pode passar alguns parametros d coordenadas).

estou aberto a sugestoes!

**Comment by betodasilva** [comment]
Massa!

É bem daora fazer um app. Fica bem controlada a distribuição mas pode demorar no quesito publicação, não acha? Principalmente na Apple Store (que inclusive precisa da conta de dev).

Quanto as features, acho bem de boas de serem feitas. Acredito que o Waze é viável também.

Mas tudo isso depende do prazo que você tem em mente pra lançar pelo menos um beta...

**Comment by felipefanucchi** [comment]
Sim voce tem razão! 

Mas a ideia também é ir de encontro com algo que as pessoas estão mais acostumadas.

Sem contar que a publicação na Apple é bem mais CARA haha. Como é um projeto pequeno, a princípio, pensei em lança-lo só para android e caso vingue, lançar pra apple também.

Em questão de marketing, não é a melhor estratégia, estou ciente haha, porém pensando em custos, acho q podemos manter somente para android no início.

Sobre o waze, é algo simples, dei uma pesquisada aqui e só vamos precisar utilizar o deep link e passar alguns parametros, acho que pode dar bem certo.

A ideia é ser simples e utilizarmos o que temos no mercado a nosso favor, whatsapp para o chat e waze para o trajeto por exemplo.

Quanto a prazo, pretendo fechar a API até sexta e focar sábado e domingo no APP pra ter algo na segunda e tentar lançar na loja o quanto antes.

**Comment by felipefanucchi** [comment]
Referente a tecnologias. 

Temos em mãos o Ionic, React Native e Native Script.

Eu particularmente opto por RN, pois tenho mais experiência do que em ambas citadas.

Quando digo que tenho experiência, é somente em questão de estudos mesmo tanto que este APP é um deles, porém com uma proposta diferente e que pode vir a ajudar pessoas de fato.
 
Você topa? Faz um fork da api, dá uma olhada em como está o andamento, caso tenha alguma sugestão, melhoria, estamos aí, vamos aprender juntos!

**Comment by betodasilva** [comment]
React Native sem dúvidas.

Estou no mesmo barco de aprendizado, fiz algumas coisas mas ainda empolgado pra explorar mais!

Um pedido: teria como você listar as tarefas que têm pendentes antes de codar? 

As que tem agora estão todas em 'done'. Daí não se sabe o que tem pra fazer.

Assim fica mais fácil pra contribuir, porque neste momento só você tem o melhor panorama do projeto.

E se possível, assim que puder, adiciona também no readme uma descrição mais detalhada do projeto. Somente 'o que é' e 'como funciona' mesmo. Já vai ajudar bastante no entendimento geral.

**Comment by felipefanucchi** [comment]
@betodasilva Lancei uma lista de tarefas lá na aba projetos, se tiver alguma dúvida, só me falar

**Comment by betodasilva** [comment]
Show, @felipefanucchi. 

Vim comentar duas paradinhas.

O que vc acha de usar [mobx](https://github.com/mobxjs/mobx) pra state management do app ao invés de redux? Já ouviu falar?

Estamos usando num app da weef e é bem mais simples e também escalável. Mesmo se ainda não viu a curva de aprendizado é bem simples. Mas você avalia aí o melhor.

Outro ponto, aproveitando o comentário.

Vou dar um help na criação dos emails com mjml.

Levantei uma página no figma e fiz um design simples (que a gnt pode ir modificando de acordo).

Tô fazendo o tracking no meu fork e pretendo fazer o pull request até o fds.

Dá uma olhada: 
https://www.figma.com/file/DM0mBoDEFJD4oNxYvRZJzA/BuscaPraMim?node-id=0%3A1

**Comment by felipefanucchi** [comment]
Vamo manda bala nesse mobx aí mano.

Eu adorei o layout que tu fez, não mudaria nada haha, só abrir um PR, fica a vontade, se tiver alguma sugestão d melhoria pro código também, tmj!

**Comment by felipefanucchi** [comment]
@betodasilva Beleza?

Cara, demorei um pouco pra iniciar o app, mas comecei haha.

Ontem eu foquei em criar toda a estrutura de navegação (somente o esqueleto) montei os stack navigators, para o fluxo d login e para as internas do app em si.

Hoje criei uma estrutura/estilo basicos para as telas de autenticação.

Referente ao MobX, estava pensando em nao adicionar de cara, ontem estava pesquisando e me deparei com a ContextAPI, achei bem interessante, acredito que será o suficiente por ora, mas caso surja a necessidade, nao vejo problema em inserirmos.

https://github.com/felipefanucchi/buscapramim_app Vou te adicionar como colaborador. 

Esse frontend eu fiz da minha cabeça e o mais simples possivel.

A tarde pretendo criar uma tela com ReactJS para o usuário resetar a senha e subir pelo netlify.

Enfim, qualquer sugestão de melhoria, seja refatoração, estilo, layout, o q for, só me dar um toque.

Eu nao utilizei styled components, acredito que seria uma boa, mas acho q a principio, podemos focar em uma v1 e dps podemos vir refatorando tudo, acho q é até mais interessante pro aprendizado. 

Enfim, desculpa a demora pra dar um feedback, hoje mesmo vou tentar criar as tarefas do que precisa ser feito.

Valeu <3
