### ISSUE TITLE
Cadastro/mapeamento dos produtos e estabelecimentos

### ISSUE THREAD

**Issue by betodasilva** [felipefanucchi/buscapramim_api#5]
Entendo que o projeto tá em fase inicial, provavelmente falta bastante coisa pra adicionar na descrição do projeto, mas essa foi minha maior dúvida, que já fica como _Feature Request_ pro README.md do projeto.

- Como vai ser feito o cadastro dos produtos? 
- Os estabelecimentos vão ser mapeados por alguma API (tipo gmaps)?

**Comment by felipefanucchi** [comment]
oi @betodasilva, acho uma boa ideia criarmos uma feature para cadastrarmos estabelecimentos.

mas a ideia a principio é que quando eu decida ir ao mercado ou farmácia, ou o que seja, eu abrir o app antes e ver se alguem nas proximidades precisa de algo.

O cadastro de estabelecimento seria mais pra caso eu esteja disposto a ir além disso, mas acho q podemos implementar como uma feature pós MVP.

Referente aos produtos, cada usuário poderá cadastrar suas necessidades, independente do que seja e ficará atrelado ao usuário. 

Podemos criar uma issue somente para esta parte do estabelecimento e colocar como feature. o q acha?

**Comment by betodasilva** [comment]
Ah, entendi @felipefanucchi. Foi mal entendimento do funcionamento geral mesmo, hehe. Mas valeu a explicação, ficou mais claro.

Concordo que fique pro pós MPV. E daí acho que podemos fechar esta issue e reabrir/criar uma nova quando chegar o momento certo.
